sudo: false

language: python

python:
    - "3.6"

install:
    - pip install ads titlecase

addons:
    apt:
        packages:
            - texlive-xetex
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - latex-xcolor
            - lmodern
            - texlive-pictures

script:
    - make

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
        cd $TRAVIS_BUILD_DIR
        git checkout --orphan $TRAVIS_BRANCH-pdf
        git rm -rf .
        git add -f cv.pdf cv_nopubs.pdf cv_onepage.pdf
        rev=$(git rev-parse --short HEAD)
        git -c user.name='travis' -c user.email='travis' commit -m "rebuild pdf at ${rev}"
        git push -q -f https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
    fi

env:
    global:
        - secure: IoX4fDvlXiiLI2F6s1o+OqJ53yt/uNZxcOLmyTWF4IEBMwbi5hc78tH8W1oB1MMAd7+oVaDl9b667MYRHBLu9OvSmz6QvIbJM5e33X4fZ6Y0Df98RxmjrxbKomtIV2Y/1Y/NcQzMuSsqi7UTj79iMnlj0mT3S+pMqHOtdrDaXDmigd4fXcJ26N9aIyJJBglqu4bXrFysaU1OeRmGpfkN5MLSPh2NcHwxV3/h9Z6urf6i99RLx6xxQr6w+HP+IopcWSk5hN7U6J10msTCSxK2Ao/jxAu7hsv5tHoawnYqD6fGlSWmJVbkCr9x60LXZ5990DHNfUhN/BU0usyHf65XlNxXlP0QlDq+EZVkv8xxC/mHV9SH9Phzjio0mfZHcfcKeewUo/0e1UMaTzylywhfM+O/kQI6qWDyVkqPwcvwTuXyDgBOK+DQx5/puzlV1SbQUSgrFlk1Yn1a/6lRegL8mN5wK1mZgVVKX7ueX1ZonYfQ8LBSXYiI/Sc8+JKxG8kaAsUJyrBpGOd3EqzThhr2cyNQ+J6OiE55B+tIO38+cIHCu9nl+gh23E8DdIIb1hHU9204WRGqYNb1A5H1GDbx9ylkgekNdDvyBHiRuCbOJjqJ5mQpsTZfMmaGZ0abIj7LGpiX21kEJU+4soBmoJlOvXeLcL1hGy1ZRyqpjN1n/DE=
